### ISSUE TITLE
Error while sending Command and its acknowledgement 

### ISSUE THREAD

**Issue by nparasher** [avnet-iotconnect/iotc-generic-c-sdk#3]
event>>> {"cmdType":"0x01","data":{"cpid":"my-cpid","guid":"my-guid","uniqueId":"my-UID","command":"CMD01","ack":false,"ackId":"d4f8927f-0725-4119-8f64-9dbe95844a0f","cmdType":"0x01"}}
command: CMD01 status=Failed: Not implemented
Sent CMD ack: {"mt":5,"t":"2022-03-02T10:36:38.000Z","uniqueId":"my-UID","cpId":"my-cpid","sdk":{"l":"M_C","v":"2.0","e":"QA"},"d":{"ackId":"d4f8927f-0725-4119-8f64-9dbe95844a0f","msg":"Not implemented","st":4}}
Error: Time:Wed Mar  2 16:06:38 2022 File:E:\SDK\AVNET_SDK\Orignal\iotc-generic-c-sdk\lib\azure-iot-sdk-c\c-utility\adapters\tlsio_schannel.c Func:on_underlying_io_bytes_received Line:977 [0x80090330] The specified data could not be decrypted.

event>>> {"cmdType":"0x01","data":{"cpid":"my-cpid","guid":"my-guid","uniqueId":"my-UID","command":"CMD01","ack":false,"ackId":"d4f8927f-0725-4119-8f64-9dbe95844a0f","cmdType":"0x01"}}
command: CMD01 status=Failed: Not implemented
Sent CMD ack: {"mt":5,"t":"2022-03-02T10:36:42.000Z","uniqueId":"my-UID","cpId":"my-cpid","sdk":{"l":"M_C","v":"2.0","e":"QA"},"d":{"ackId":"d4f8927f-0725-4119-8f64-9dbe95844a0f","msg":"Not implemented","st":4}}
Error: Failed to send message: {"mt":5,"t":"2022-03-02T10:36:42.000Z","uniqueId":"my-UID","cpId":"my-cpid","sdk":{"l":"M_C","v":"2.0","e":"QA"},"d":{"ackId":"d4f8927f-0725-4119-8f64-9dbe95844a0f","msg":"Not implemented","st":4}}. Client is not connected.
![cmd issue](https://user-images.githubusercontent.com/8564511/156348343-81768396-1add-4eb8-a592-af210dbb6a8f.jpg)

Please see the above error message and image when I am sending the command from Iotconnect, SDK receives the event and sends ACK as well but gets an error after that.

**Comment by nik-markovic** [comment]
This is an endless recursion issue.

- the main loop calls IoTHubDeviceClient_LL_DoWork
- IoTHubDeviceClient_LL_DoWork triggers a c2d callback 
- c2d callback wants to send an IoTConnect message ack to confirm it
- send_message() wants to confirm the message at MQTT level and  wants to loop on IoTHubDeviceClient_LL_DoWork in order to get an MQTT confirmation. 
- IoTHubDeviceClient_LL_DoWork again triggers the same c2d message callback for some reason.

The workaround is to know that you are inside a callback and not attempt to call IoTHubDeviceClient_LL_DoWork
